# Generated by Django 4.0.2 on 2022-02-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image_url', models.CharField(max_length=50)),
                ('forest_type', models.CharField(max_length=13)),
                ('short_description', models.CharField(max_length=50)),
                ('long_description', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('area_hectares', models.PositiveIntegerField()),
            ],
        ),
    ]
