# Generated by Django 4.0.2 on 2022-02-25 07:53

from django.db import migrations

forest_1 = {
    'name': 'Amazon Rainforest',
    'image_url': 'https://bit.ly/3LTz41b',
    'type': 'conservation',
    'short_description': 'A large rainforest in Brazil.',
    'latitude': 123,
    'longitude': 456,
    'area_hectares': 24000,
    'country': 'Brazil',
    'long_description': 'The Amazon rainforest, alternatively, the Amazon jungle or Amazonia, is a moist broadleaf tropical rainforest in the Amazon biome that covers most of the Amazon basin of South America. (credit Wikipedia)',
}
forest_2 = {
    'id': 2,
    'name': 'Olympic National Forest',
    'image_url': 'https://bit.ly/3LYarAk',
    'type': 'reforestation',
    'short_description': 'A forest in Washington.',
    'latitude': 2341,
    'longitude': 32450,
    'area_hectares': 1000,
    'country': 'United States',
    'long_description': 'Olympic National Forest is a U.S. National Forest located in Washington, USA. With an area of 628,115 acres (2,541.89 km2), it nearly surrounds Olympic National Park and the Olympic Mountain range.',
}
forest_3 = {
    'id': 3,
    'name': 'Valdivian Rainforest',
    'image_url': 'https://bit.ly/3vh7Awv',
    'type': 'conservation',
    'short_description': 'A rainforest in Chile.',
    'latitude': 123,
    'longitude': 456,
    'area_hectares': 300,
    'country': 'Chile',
    'long_description': 'The Valdivian temperate forests (NT0404) is an ecoregion on the west coast of southern South America, in Chile and extending into Argentina. It is part of the Neotropical realm. The forests are named after the city of Valdivia. The Valdivian temperate rainforests are characterized by their dense understories of bamboos, ferns, and for being mostly dominated by evergreen angiosperm trees with some deciduous specimens, though conifer trees are also common.',
}


def make_default_forests(apps, schema_editor):
    Forest = apps.get_model('forests', 'Forest')

    for forest in [forest_1, forest_2, forest_3]:
        forest_row = Forest()
        forest_row.name = forest['name']
        forest_row.image_url = forest['image_url']
        forest_row.forest_type = forest['type']
        forest_row.short_description = forest['short_description']
        forest_row.long_description = forest['long_description']
        forest_row.country = forest['country']
        forest_row.latitude = forest['latitude']
        forest_row.longitude = forest['longitude']
        forest_row.area_hectares = forest['area_hectares']
        forest_row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forests', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_default_forests),
    ]
