# Generated by Django 4.0.2 on 2022-02-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forests', '0002_auto_20220225_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('carbon_stored_tonnes', models.IntegerField()),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forests.forest')),
            ],
        ),
    ]
