# Generated by Django 4.0.2 on 2022-02-25 20:46

from django.db import migrations
import datetime


def make_default_health_metrics(apps, schema_editor):
    Forest = apps.get_model('forests', 'Forest')
    ForestHealth = apps.get_model('forests', 'ForestHealth')

    forests = Forest.objects.all()
    assert len(forests) >= 3

    # Health metrics for first forest
    health_metric = ForestHealth()
    health_metric.forest = forests[0]
    health_metric.date = datetime.date(2022, 1, 1)
    health_metric.carbon_stored_tonnes = 3000
    health_metric.save()

    health_metric = ForestHealth()
    health_metric.forest = forests[0]
    health_metric.date = datetime.date(2022, 1, 31)
    health_metric.carbon_stored_tonnes = 3075
    health_metric.save()

    # Health metrics for second forest
    health_metric = ForestHealth()
    health_metric.forest = forests[1]
    health_metric.date = datetime.date(2022, 1, 1)
    health_metric.carbon_stored_tonnes = 4150
    health_metric.save()

    health_metric = ForestHealth()
    health_metric.forest = forests[1]
    health_metric.date = datetime.date(2022, 1, 31)
    health_metric.carbon_stored_tonnes = 4030
    health_metric.save()

    # Health metrics for third forest
    health_metric = ForestHealth()
    health_metric.forest = forests[2]
    health_metric.date = datetime.date(2022, 1, 1)
    health_metric.carbon_stored_tonnes = 1500
    health_metric.save()

    health_metric = ForestHealth()
    health_metric.forest = forests[2]
    health_metric.date = datetime.date(2022, 1, 31)
    health_metric.carbon_stored_tonnes = 1523
    health_metric.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forests', '0003_foresthealth'),
    ]

    operations = [
        migrations.RunPython(make_default_health_metrics),
    ]
